[tool.isort]
multi_line_output = 5
include_trailing_comma = true
use_parentheses = true
ensure_newline_before_comments = true
color_output = true

[tool.flake8]
extend-ignore = "E501,"

[tool.pytest.ini_options]

addopts = "--rootdir src"

filterwarnings = [
	"ignore:.*ugettext_lazy:django.utils.deprecation.RemovedInDjango40Warning:wagtailnews.menu",
	"ignore:.*ugettext_lazy:django.utils.deprecation.RemovedInDjango40Warning:wagtailnews.models",
	"ignore::django.utils.deprecation.RemovedInDjango40Warning:wagtail.admin.signals",
	"ignore::django.utils.deprecation.RemovedInDjango40Warning:wagtail.core.signals",
	"ignore::django.utils.deprecation.RemovedInDjango40Warning:wagtail.documents.models",
	"ignore::django.utils.deprecation.RemovedInDjango40Warning:wagtailmetadata",
	"ignore::django.utils.deprecation.RemovedInDjango40Warning:wagtailnews.signals",
	"ignore::django.utils.deprecation.RemovedInDjango40Warning:wagtailnews.urls",
	"ignore::django.utils.deprecation.RemovedInDjango40Warning:wagtailnews.wagtail_hooks",
	"ignore:No directory at:UserWarning:whitenoise.base",
]

testpaths = [
	"src/tests",
]
