# Generated by Django 3.1.7 on 2021-04-07 13:36

from django.db import migrations
from django.db.models import F, Value, functions


def forwards(apps, schema):
    Page = apps.get_model("pages.Page")
    Page.objects.update(body=functions.Concat(
        Value('[{"type": "rich_content", "value":'),
        F("body"),
        Value('}]'),
    ))


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
