# Generated by Django 3.1.7 on 2021-04-10 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_show_toc'),
    ]

    operations = []
