# Generated by Django 3.1.7 on 2021-04-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_add_cash_donations_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='abn',
            field=models.CharField(default='', help_text='The ABN put on invoices and the like', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='name',
            field=models.CharField(default='Jax Ewin', help_text='Your name, used on invoices and other such things.', max_length=200),
            preserve_default=False,
        ),
    ]
