# Generated by Django 3.1.7 on 2021-04-10 07:13

import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stripe_id', models.CharField(blank=True, help_text='The ID of the payment in Stripe, if it was done online', max_length=100)),
            ],
            options={
                'ordering': ['-date', '-created'],
            },
        ),
        migrations.CreateModel(
            name='DonatePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.StreamField([])),
                ('success_body', wagtail.core.fields.StreamField([])),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
    ]
