# Generated by Django 3.1.7 on 2021-04-12 12:38
import functools

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks
from django.db import migrations

import jaxattax.common.blocks
from jaxattax.utils.migrations import StreamFieldDataMigration


def rename_block(from_name, to_name, blocks):
    for block in blocks:
        if block['type'] == from_name:
            block = block.copy()
            block['type'] = to_name
        yield block


def forwards(instance, data):
    # A few things changed:
    # In rich_content blocks, large_image was renamed to captioned_image
    # side_image blocks were nested into rich_content blocks
    new_data = []
    for child in data:
        if child['type'] == 'rich_content':
            child['value'] = list(rename_block('large_image', 'captioned_image', child['value']))
        elif child['type'] == 'side_image':
            child = {'type': 'rich_content', 'value': [child]}
        new_data.append(child)
    return new_data


def split_side_image(all_blocks):
    rich_content_blocks = []
    for child in all_blocks:
        if child['type'] == 'side_image':
            if rich_content_blocks:
                yield {'type': 'rich_content', 'value': rich_content_blocks}
                rich_content_blocks = []
            yield child


def reduce_split_side_image(new_blocks, next_block):
    if next_block['type'] == 'side_image':
        new_blocks.append(next_block)
        return new_blocks

    if new_blocks and new_blocks[-1]['type'] == 'rich_content':
        rich_content = new_blocks[-1]
    else:
        rich_content = {'type': 'rich_content', 'value': []}
        new_blocks.append(rich_content)
    rich_content['value'].append(next_block)
    return new_blocks


def backwards(instance, data):
    new_data = []
    for child in data:
        if child['type'] == 'rich_content':
            all_blocks = list(rename_block('captioned_image', 'large_image', child['value']))
            new_data.extend(functools.reduce(reduce_split_side_image, all_blocks, []))
        else:
            new_data.append(child)
    return new_data


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_add_cashdonation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(group=jaxattax.common.blocks.Group(name='Text', order=100), icon='fa-header')), ('subheading', wagtail.core.blocks.CharBlock(group=jaxattax.common.blocks.Group(name='Text', order=100), icon='fa-header')), ('rich_text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'document-link', 'ol', 'ul', 'hr', 'embed'], group=jaxattax.common.blocks.Group(name='Text', order=100), label='Text')), ('hero_text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'document-link', 'ol', 'ul', 'hr', 'embed'], group=jaxattax.common.blocks.Group(name='Big and bold', order=200), help_text='Big and bold, use for important text at the start of a page.', label='Hero text')), ('hero_image', wagtail.images.blocks.ImageChooserBlock(group=jaxattax.common.blocks.Group(name='Big and bold', order=200), help_text='Big image, use as the feature image of a page.', label='Hero image')), ('buttons', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock()), ('link', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())]))]))), ('captioned_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('full-width', 'Full width'), ('left', 'Left'), ('right', 'Right')])), ('caption', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'document-link'], help_text='Some short text describing the image', required=False))])), ('side_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')])), ('content', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(group=jaxattax.common.blocks.Group(name='Text', order=100), icon='fa-header')), ('subheading', wagtail.core.blocks.CharBlock(group=jaxattax.common.blocks.Group(name='Text', order=100), icon='fa-header')), ('rich_text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'document-link', 'ol', 'ul', 'hr', 'embed'], group=jaxattax.common.blocks.Group(name='Text', order=100), label='Text'))]))])), ('table_of_contents', wagtail.core.blocks.StructBlock([])), ('cash_donations', wagtail.core.blocks.StructBlock([])), ('donate', wagtail.core.blocks.StructBlock([]))]),
        ),
        migrations.AlterField(
            model_name='donatepage',
            name='success_body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(group=jaxattax.common.blocks.Group(name='Text', order=100), icon='fa-header')), ('subheading', wagtail.core.blocks.CharBlock(group=jaxattax.common.blocks.Group(name='Text', order=100), icon='fa-header')), ('rich_text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'document-link', 'ol', 'ul', 'hr', 'embed'], group=jaxattax.common.blocks.Group(name='Text', order=100), label='Text')), ('hero_text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'document-link', 'ol', 'ul', 'hr', 'embed'], group=jaxattax.common.blocks.Group(name='Big and bold', order=200), help_text='Big and bold, use for important text at the start of a page.', label='Hero text')), ('hero_image', wagtail.images.blocks.ImageChooserBlock(group=jaxattax.common.blocks.Group(name='Big and bold', order=200), help_text='Big image, use as the feature image of a page.', label='Hero image')), ('buttons', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock()), ('link', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())]))]))), ('captioned_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('full-width', 'Full width'), ('left', 'Left'), ('right', 'Right')])), ('caption', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'document-link'], help_text='Some short text describing the image', required=False))])), ('side_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')])), ('content', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(group=jaxattax.common.blocks.Group(name='Text', order=100), icon='fa-header')), ('subheading', wagtail.core.blocks.CharBlock(group=jaxattax.common.blocks.Group(name='Text', order=100), icon='fa-header')), ('rich_text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'document-link', 'ol', 'ul', 'hr', 'embed'], group=jaxattax.common.blocks.Group(name='Text', order=100), label='Text'))]))])), ('table_of_contents', wagtail.core.blocks.StructBlock([])), ('cash_donations', wagtail.core.blocks.StructBlock([]))]),
        ),
        StreamFieldDataMigration(
            model_name='donatepage',
            name='body',
            forwards_code=forwards,
            backwards_code=backwards,
        ),
        StreamFieldDataMigration(
            model_name='donatepage',
            name='success_body',
            forwards_code=forwards,
            backwards_code=backwards,
        ),
    ]
