# Generated by Django 3.1.7 on 2021-04-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = []
