# Generated by Django 3.1.7 on 2021-04-08 14:51

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210407_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(icon='fa-header')), ('subheading', wagtail.core.blocks.CharBlock(icon='fa-header')), ('rich_text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'document-link', 'ol', 'ul', 'hr', 'embed'], label='Text')), ('buttons', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock()), ('link', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())]))]))), ('large_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('full-width', 'Full width'), ('left', 'Left'), ('right', 'Right')])), ('caption', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'document-link'], help_text='Some short text describing the image', required=False))])), ('table_of_contents', wagtail.core.blocks.StructBlock([]))]),
        ),
    ]
