# Generated by Django 3.1.7 on 2021-04-10 06:51

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210408_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(icon='fa-header')), ('subheading', wagtail.core.blocks.CharBlock(icon='fa-header')), ('rich_text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'document-link', 'ol', 'ul', 'hr', 'embed'], label='Text')), ('large_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('full-width', 'Full width'), ('left', 'Left'), ('right', 'Right')])), ('caption', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'document-link'], help_text='Some short text describing the image', required=False))]))]),
        ),
    ]
