# Generated by Django 3.1.7 on 2021-04-12 12:38
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations

import jaxattax.blocks
from jaxattax.utils.migrations import StreamFieldDataMigration


def rename_block(from_name, to_name, blocks):
    for block in blocks:
        if block['type'] == from_name:
            block = block.copy()
            block['type'] = to_name
        yield block


def forwards(instance, data):
    return list(rename_block('large_image', 'captioned_image', data))


def backwards(instance, data):
    return list(rename_block('captioned_image', 'large_image', data))


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsitem_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(group=jaxattax.blocks.Group(name='Text', order=100), icon='fa-header')), ('subheading', wagtail.core.blocks.CharBlock(group=jaxattax.blocks.Group(name='Text', order=100), icon='fa-header')), ('rich_text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'document-link', 'ol', 'ul', 'hr', 'embed'], group=jaxattax.blocks.Group(name='Text', order=100), label='Text')), ('captioned_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('full-width', 'Full width'), ('left', 'Left'), ('right', 'Right')])), ('caption', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'document-link'], help_text='Some short text describing the image', required=False))]))]),
        ),
        StreamFieldDataMigration(
            model_name='newsitem',
            name='body',
            forwards_code=forwards,
            backwards_code=backwards,
        ),
    ]
